#!/bin/bash

SCRIPTS_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPTS_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
    vim $SCRIPT_FILE
else
    echo '#!/bin/bash' > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
    vim $SCRIPT_FILE
fi

